# Update Checker Settings
update-checker:
  enable: true
  console: true # Post message to console
  op: true # Send update notification to opped players on join

# Language, specify the language file to use, for example `en_US` which will load `/lang/en_US.json`
language: "en_US"

cooldowns:
  war:
    government:
      offensive:
        default: 14 # Days
        mercenary: 30 # Days

      defensive:
        default: 7 # Days
    resident:
      offensive:
        default: 14 # Days
        mercenary: 30 # Days

      defensive:
        default: 7 # Days

war:
  required-playtime: 60 # Minutes (Does not apply to force-joined players)
  wartime-duration: 120 # Duration of wartime in minutes

battles:
  teleport-world-whitelist: # Worlds players may teleport from (prevents getting stuck in lobby worlds) (usage of t spawn etc)
    - "spawn"
  sieges:
    range: 500 # The radius in blocks around the siege point that will be considered the battlefield
    duration: 60 # The duration of the siege in minutes
    trigger:
      range: 250 # The range in blocks around the siege point that a siege can be triggered from
      # When these items are used in proximity to a town by a war-leader or captain they will trigger a siege for the closest town
      items:
        - "minecraft:goat_horn"
    points:
      attacker-victory: 50 # Given to attackers if they win
      defender-loss: 5 # Given to defenders if they lose
      attacker-loss: 1 # Given to attackers if they lose
      defender-victory: 10 # Given to defenders if they win

respawns:
  # Seconds a player must wait before respawning
  time: 15
  # If users should need the "alathranwars.death.spectate" permission to enable respawns
  permission: false
  # Worlds to enable respawning from (Leave empty to disable)
  whitelisted-worlds: []
  # Commands allowed to be run while respawning (Leave empty to disable)
  whitelisted-commands: []
  # Causes that will not trigger respawning (Leave empty to disable)
  # (https://jd.papermc.io/paper/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html)
  blacklisted-damage-causes: []

  proxy:
    # Time in seconds it takes for a spawn to re-enable after being proxied
    reenable-time: 10 # Seconds
    min-players: 1 # Required players to proxy a spawn
    range: 8 # The range around a spawn point to check for proxying players

  # Settings related to rally points (Placeable spawn points)
  rallies:
    # The cooldown a player must wait before being able to place another rally
    placement-cooldown: 5 # Minutes

    # Time in seconds it takes for a rally to be removed if proxied
    proxy-delete: 60 # Seconds

    # The ranges in blocks rally points need to be away from other types of spawns
    min-range-town-friendly: 150
    min-range-outpost-friendly: 100
    min-range-rally-friendly: 120
    min-range-town-hostile: 100
    min-range-outpost-hostile: 50
    min-range-rally-hostile: 25

colors:
  particles:
    friendly: "#5555FF"
    neutral: "#FFFF55"
    hostile: "#FF5555"
  nametags:
    prefix:
      friendly: "<blue>"
      neutral: "<yellow>"
    hostile: "<red>"
    suffix:
      friendly: "</blue>"
      neutral: "</yellow>"
      hostile: "</red>"
