[versions]
java = "21"
paper-api = "1.21.7-R0.1-SNAPSHOT"
paper-run = "1.21.7"
crate = "4.0.0-RC.5"
commandapi = "10.1.2"
flyway = "11.1.0"
jooq = "3.20.5"

[libraries]
# Core dependencies
annotations = "org.jetbrains:annotations:26.0.2"
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
morepaperlib = "space.arim.morepaperlib:morepaperlib:0.4.4"

# API dependencies
javasemver = "io.github.milkdrinkers:javasemver:1.0.2"
versionwatch = "io.github.milkdrinkers:versionwatch:1.0.2"
wordweaver = "io.github.milkdrinkers:wordweaver:0.0.7"
crate-api = { module = "com.github.milkdrinkers:crate-api", version.ref = "crate" }
crate-yaml = { module = "io.github.milkdrinkers:crate-yaml", version.ref = "crate" }
colorparser = "io.github.milkdrinkers:colorparser-paper:4.1.0"
threadutil-bukkit = "io.github.milkdrinkers:threadutil-bukkit:1.4.0"
commandapi-shade = { module = "dev.jorel:commandapi-bukkit-shade-mojang-mapped", version.ref = "commandapi" }
triumph-gui = "dev.triumphteam:triumph-gui-paper:3.1.13-SNAPSHOT"
itemutils = "io.github.milkdrinkers:itemutils:1.1.0"

# Plugin dependencies
bstats = "org.bstats:bstats-bukkit:3.1.0"
vault = "com.github.MilkBowl:VaultAPI:1.7.1"
packetevents = "com.github.retrooper:packetevents-spigot:2.9.5"
entitylib = "com.github.Tofaa2.EntityLib:spigot:cef23ea82d"
placeholderapi = "me.clip:placeholderapi:2.11.6"
towny = "com.palmergames.bukkit.towny:towny:0.101.2.0"
tabapi = "com.github.NEZNAMY:TAB-API:5.2.5"
unlimitednametags = "com.github.alexdev03:UnlimitedNametags:1.6.9"
gsit = "com.github.gecolay.GSit:GSit:2.4.2"
essentialsx-core = "net.essentialsx:EssentialsX:2.21.1"
essentialsx-spawn = "net.essentialsx:EssentialsXSpawn:2.21.1"
settlers = "com.github.milkdrinkers:Settlers:main-SNAPSHOT"
lockpicking = "com.github.Alathra:SimpleLockpicking:main-SNAPSHOT"
gravesx = "com.ranull:GravesX:4.9.8.1-api"
skulls = "ca.tweetzy:skulls:v3.23.0"
headsplus = "com.github.Thatsmusic99:HeadsPlus:v6.10.5-SNAPSHOT-1"

# Database dependencies
hikaricp = "com.zaxxer:HikariCP:7.0.0"
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-mysql = { module = "org.flywaydb:flyway-mysql", version.ref = "flyway" }
jooq = { module = "org.jooq:jooq", version.ref = "jooq" }
jakarta = "jakarta.xml.bind:jakarta.xml.bind-api:4.0.2" # Compiler bug, see: https://github.com/jOOQ/jOOQ/issues/14865#issuecomment-2077182512

# JDBC drivers
h2 = "com.h2database:h2:2.3.232"
sqlite = "org.xerial:sqlite-jdbc:3.50.3.0"
mysql = "com.mysql:mysql-connector-j:9.4.0"
mariadb = "org.mariadb.jdbc:mariadb-java-client:3.5.4"

# Testing
junit-bom = "org.junit:junit-bom:5.13.4"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }
slf4j = "org.slf4j:slf4j-simple:2.0.17"
testcontainers-bom = "org.testcontainers:testcontainers-bom:1.21.3"
testcontainers-jupiter = { module = "org.testcontainers:junit-jupiter" }
testcontainers-mysql = { module = "org.testcontainers:mysql" }
testcontainers-mariadb = { module = "org.testcontainers:mariadb" }

[bundles]
flyway = ["flyway-core", "flyway-mysql"]
jdbcdrivers = ["h2", "sqlite", "mysql", "mariadb"]
junit = ["junit-jupiter", "junit-platform"]
testcontainers = ["testcontainers-jupiter", "testcontainers-mysql", "testcontainers-mariadb"]

[plugins]
shadow = "com.gradleup.shadow:9.0.2"
run-paper = "xyz.jpenilla.run-paper:3.0.0"
plugin-yml-bukkit = "de.eldoria.plugin-yml.bukkit:0.8.0"
plugin-yml-paper = "de.eldoria.plugin-yml.paper:0.8.0"
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
jooq = { id = "org.jooq.jooq-codegen-gradle", version.ref = "jooq" }