[versions]
paper-api = "1.21.5-R0.1-SNAPSHOT"
paper-run = "1.21.8"
crate = "4.0.0-RC.4"
commandapi = "10.1.2"
flyway = "11.11.1"
jooq = "3.20.6"

[libraries]
# Core dependencies
annotations = "org.jetbrains:annotations:26.0.2"
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
morepaperlib = "space.arim.morepaperlib:morepaperlib:0.4.4"

# API dependencies
wordweaver = "io.github.milkdrinkers:wordweaver:0.0.7"
crate-api = { module = "io.github.milkdrinkers:crate-api", version.ref = "crate" }
crate-yaml = { module = "io.github.milkdrinkers:crate-yaml", version.ref = "crate" }
colorparser = "io.github.milkdrinkers:colorparser-paper:4.0.0-RC.1"
threadutil = "io.github.milkdrinkers:threadutil-bukkit:1.2.0"
command-api-paper = { module = "dev.jorel:commandapi-bukkit-shade-mojang-mapped", version.ref = "commandapi" }
entitylib = "me.tofaa.entitylib:spigot:2.4.10-SNAPSHOT"
tab-api = "com.github.neznamy:tab-api:5.2.5"

# Plugin dependencies
bstats = "org.bstats:bstats-bukkit:3.1.0"
vault = "com.github.MilkBowl:VaultAPI:1.7.1"
placeholderapi = "me.clip:placeholderapi:2.11.6"
towny = "com.palmergames.bukkit.towny:towny:0.101.2.0"
gsit = "com.github.Gecolay.GSit:core:1.9.0"
packetevents = "com.github.retrooper:packetevents-spigot:2.5.0"

# Database dependencies
hikaricp = "com.zaxxer:HikariCP:7.0.2"
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-mysql = { module = "org.flywaydb:flyway-mysql", version.ref = "flyway" }
jooq = { module = "org.jooq:jooq", version.ref = "jooq" }
jakarta = "jakarta.xml.bind:jakarta.xml.bind-api:4.0.2" # Compiler bug, see: https://github.com/jOOQ/jOOQ/issues/14865#issuecomment-2077182512

# JDBC drivers
h2 = "com.h2database:h2:2.3.232"
sqlite = "org.xerial:sqlite-jdbc:3.50.3.0"
mysql = "com.mysql:mysql-connector-j:9.4.0"
mariadb = "org.mariadb.jdbc:mariadb-java-client:3.5.5"

# Testing
junit-bom = "org.junit:junit-bom:5.13.4"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }
slf4j = "org.slf4j:slf4j-simple:2.1.0-alpha1"
testcontainers-bom = "org.testcontainers:testcontainers-bom:1.21.3"
testcontainers-jupiter = { module = "org.testcontainers:junit-jupiter" }
testcontainers-mysql = { module = "org.testcontainers:mysql" }
testcontainers-mariadb = { module = "org.testcontainers:mariadb" }

[bundles]
flyway = ["flyway-core", "flyway-mysql"]
jdbcdrivers = ["h2", "sqlite", "mysql", "mariadb"]
junit = ["junit-jupiter", "junit-platform"]
testcontainers = ["testcontainers-jupiter", "testcontainers-mysql", "testcontainers-mariadb"]

[plugins]
publisher = "com.vanniktech.maven.publish:0.34.0"
shadow = "com.gradleup.shadow:9.0.2"
run-paper = "xyz.jpenilla.run-paper:2.3.1"
plugin-yml-bukkit = "net.minecrell.plugin-yml.bukkit:0.6.0"
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
jooq = { id = "org.jooq.jooq-codegen-gradle", version.ref = "jooq" }